# Generated by Django 2.0.5 on 2018-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='category',
            field=models.ManyToManyField(to='ebook.Category'),
        ),
    ]
