# Generated by Django 2.0.5 on 2018-08-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_ebook_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='category',
        ),
        migrations.AddField(
            model_name='ebook',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebook.Category'),
            preserve_default=False,
        ),
    ]
